import type { Locale } from "@/data/masks";

export const termsLegalBody: Record<Locale, readonly string[]> = {
  ro: [
    "Termeni și Condiții",
    "Termeni și condiții de utilizare a",
    "Magazinului Online www.RedlightTherapy.md",
    "1. Informații generale",
    "Prezenții Termeni și condiții de utilizare a magazinului online în continuare „Condițiile\" sunt aplicabili comenzilor pentru achiziționarea produselor și serviciilor oferite de „NLRE GROUP” SRL prin intermediul site-ului www.redlighttherapy.md în continuare numit  “Site”.",
    "Folosirea acestui Site implică acceptarea Condițiilor propuse de către „NLRE GROUP” SRL identificat cu cod fiscal 1025600008673, cod TVA 0212138, adresa juridică – Chișinău, str. Anton Crihan 20A.",
    "„NLRE GROUP” SRL își asumă dreptul de a modifica aceste prevederi, iar cea mai recentă versiune",
    "poate fi găsită pe Site, accesând rubrica „Termeni și Condiții\".",
    "Recomandăm citirea cu atenție a prezentelor Condiții. Acest Site este dedicat utilizării de către persoanele fizice și juridice care fac comenzi pentru produsele sau serviciile „NLRE GROUP” SRL.",
    "2. Descrierea produselor și preț",
    "Utilizând Site-ul aveți posibilitatea de a vă informa cu privire la produse și a plasa comenzi de achiziționare a produselor și serviciilor.",
    "Produsele sunt oferite după cum sunt prezentate pe Site și în limita stocului disponibil.",
    "Pozele produselor sunt prezentate pe Site cu titlu de informativ, iar produsele livrate pot diferi de imagini în orice mod (culoare, accesorii, aspect etc.). „NLRE GROUP” SRL și furnizorii săi își rezervă dreptul să modifice specificațiile tehnice ale produselor descrise pe Site fără o notificare prealabilă.",
    "Descrierile produselor, caracteristicile tehnice, imaginile, simbolurile a fost completate reieșind din documentele producătorilor/ reprezentanților mărcilor respective. Din acest motiv, „NLRE GROUP” SRL nu își asumă responsabilitatea pentru descrierile/caracteristicile produselor prezentate în magazinul online, acestea fiind puse la dispoziția noastră de către producătorii fiecărei mărci.",
    "Prețurile prezentate includ TVA, fiind prețurile în vigoare la momentul validării comenzii.",
    "3. Comanda",
    "La inițierea unei comenzi pe Site, aveți opțiunea de plasare a comenzii prin:",
    "- Activând butonul „Cumpără” — comandă care presupune parcurgerea tuturor pașilor de plasare a comenzii, după care un consultant va reveni cu un apel pentru confirmarea stocului și comenzii plasate.",
    "Opțiunea „Confirma comanda” nu presupune rezervarea produsului.",
    "Prin plasarea comenzii, clientul garantează ca toate datele furnizate sunt reale si corecte, in caz contrar suportând consecințele acestor erori, ca de ex. comanda întârziată, transmisă greșit etc.",
    "După plasarea comenzii, „NLRE GROUP” SRL vă va expedia un e-mail pentru confirmarea recepționării comenzii (în cazul în care a fost indicat adresa de email) sau va fi contactat telefonic de către operator pentru confirmarea acesteia.  Acest e-mail este doar o confirmare de plasare a comenzii Dvs pe site și nu reprezintă o confirmare de validare a comenzii sau de încheiere a contractului. Confirmarea comenzii se validează de către operator prin apel telefonic pînă la achitarea acestora.",
    "„NLRE GROUP” SRL poate refuza o comandă, printr-o notificare adresată clientului, fără ca o parte sa poată pretindă prejudicii, în următoarele cazuri:",
    "livrări consecutiv eșuate;",
    "date incomplete sau incorecte ale clientului;",
    "eșuarea / invalidarea tranzacției online;",
    "neacceptarea tranzacției de către banca emitentă a cardului clientului;",
    "4. Livrare",
    "Livrarea produselor se va face pe teritoriul Republicii Moldova. Pentru fiecare comandă se acceptă doar o adresa de livrare.",
    "Livrarea se efectuează de Luni pînă Sîmbătă. În ziua de Duminică livrările nu se efectuează!",
    "Livrarea se efectuează doar pentru produsele comandate. Livrarea mai multor produse cu intenția de a alege pe loc un produs nu este disponibilă.",
    "În angajamentele curierului nu intră instalarea, conectarea, demonstrarea tuturor caracteristicilor sau predarea modului de utilizarea a produsului.",
    "Dacă comanda este livrată și îndeplinește toate condițiile de garanție, dar vă răzgândiți să efectuați achiziția, va trebui să plătiți cheltuielile de transport. Prin urmare, asigurați-vă că alegeți corect produsul pe care doriți să îl achiziționați cu adevărat.",
    "Prețul livrării variază în dependentă de gabaritele și adresa destinatarului. În or. Chișinău prețul începe de la 50 lei în alte localități în dependentă de tarifele serviciilor de curierat. Operatorul va informa clientul despre costul livrării.",
    "Livrarea produselor de dimensiuni mari se efectuează până la scară sau porțile casei.",
    "Menționăm că este necesar să se producă verificarea integrală și lipsa defectelor la exterior a produselor de către cumpărător.",
    "Atenție! Clientul poate opta pentru ridicare personala în punctul de ridicare indicat pe site",
    "https://redlightteherapy.md/contacts",
    "„NLRE GROUP” SRL SRL nu poate garanta disponibilitatea în stoc a tuturor produselor prezentate pe Site. „NLRE GROUP” SRL va informa clientul despre indisponibilitatea produsului și, după caz, va rambursa sumele încasate de la client în cel mai scurt timp, dar nu mai târziu de 30 de zile, în cazul în care „NLRE GROUP” SRL nu poate onora comanda.",
    "Cu acordul clientului, „NLRE GROUP” SRL poate livra un produs similar, de o calitate și un preț echivalent cu cele solicitate inițial, în cazul indisponibilității produsului comandat.",
    "5. Drept de revocare",
    "Persoană fizică consumator, are dreptul de a revoca contractul încheiat la distanță sau în afara spațiilor comerciale, în termen de 14 zile calendaristice, începând, din ziua încheierii contractului sau din ziua în care ați intrat în posesia fizică a produsului comandat.",
    "Pentru a vă exercita dreptul de revocare urmează să depuneți o cerere scrisă de revocare în punctele de ridicare indicate pe site, împreună cu produsul returnat în starea inițială în care a fost primit, în ambalaj original, cu toate accesoriile și documentele de însoțire sau utilizând o declarație neechivocă (de exemplu, o scrisoare trimisă poșta electronic rlt@gmail.com) înainte de expirarea perioadei de revocare de 14 zile.",
    "Dacă revocați în termenul de 14 zile contractul pentru cumpărarea produselor, „NLRE GROUP” SRL va rambursa sumele plătite de dumneavoastră, nu mai târziu de 14 zile calendaristice de la data la care primim cererea dumneavoastră de revocare a contractului, cu condiția returnării produselor în stare inițială, perfectă. Vom efectua rambursarea folosind aceeași modalitate de plată ca și cea folosită pentru tranzacția inițială, fără sa fie percepute comisioane ca urmare a unei astfel de rambursări.",
    "În cazul în care produsul a fost folosit înaintea returnării (inclusiv dacă prezintă semne de deteriorări, lipsesc accesorii, ambalaje, au fost descărcate aplicații, mobila instalata, mărfurile electronice complexe au fost utilizate.), „NLRE GROUP” SRL va avea dreptul sa perceapă o despăgubire stabilită după caz, în funcție de integralitatea produselor livrate, gradul de utilizare și/sau deteriorare a produselor, despăgubire care nu poate depăși contravaloarea produselor, reieșind din prețul comercial (fără reduceri). „NLRE GROUP” SRL are dreptul sa reducă suma rambursată Clientului, pentru a acoperi suma respectivă a despăgubirii.",
    "Clientul va suporta toate costurile directe legate de returnarea produselor.",
    "În cazul plasării unei comenzi cu ridicarea produsului în punctele de ridicare indicate pe site, clientul beneficiază de o rezervare de 48 de ore. În aceste cazuri, clientul nu beneficiază de dreptul de revocare a contractului, contractul fiind încheiat ulterior, în spațiile comerciale ale „NLRE GROUP” SRL.",
    "6. Plata",
    "Plata produselor comandate conform acestor Termeni și Condiții se poate efectua la livrarea produselor sau online, prin intermediul cardului bancar.",
    "În cazul în care alegeți să faceți plata la livrare, aceasta poate fi efectuată în numerar sau cu cardul bancar.",
    "7. Garanția produsului",
    "Produsele cumpărate prin intermediul Site-ului www.redlighttherapy.md beneficiază de garanția producătorului, cu respectarea prevederilor legale în vigoare. Produsul va fi însoțit la livrare de certificat de garanție, care asigură deservire în termen de garanție, cu condiția prezentării certificatului de garanție, facturii de cumpărare și/sau bonului de casă.",
    "Adresele locurilor de preschimbare a mărfii sunt indicate pe site https://redlighttherapymd/contacts",
    "Orice litigiu apărut va fi rezolvat pe cale amiabilă. În cazul în care nu s-a reușit stingerea conflictului pe cale amiabilă, competența revine instanțelor de judecată competente.",
  ],
  ru: [
    "Условия и положения",
    "Условия использования интернет-магазина www.redlighttherapy.md",
    "1. Общая информация",
    "Настоящие Условия (далее — «Условия») применяются к заказам на приобретение товаров и услуг, предлагаемых компанией «NLRE GROUP» SRL через сайт www.redlighttherapy.md (далее — «Сайт»).",
    "Использование данного Сайта означает согласие с настоящими Условиями, установленными компанией «NLRE GROUP» SRL, фискальный код 1025600008673, код НДС 0212138, юридический адрес: г. Кишинёв, ул. Антон Крихан 20A.",
    "«NLRE GROUP» SRL оставляет за собой право изменять данные Условия, при этом актуальная версия всегда доступна на Сайте в разделе «Условия и положения».",
    "Рекомендуем внимательно ознакомиться с настоящими Условиями. Сайт предназначен для использования физическими и юридическими лицами, оформляющими заказы на товары и услуги компании «NLRE GROUP» SRL.",
    "2. Описание товаров и цены",
    "Используя Сайт, вы можете ознакомиться с товарами и оформить заказ на их приобретение.",
    "Товары предлагаются в том виде, в котором они представлены на Сайте, и в пределах наличия на складе.",
    "Изображения товаров носят информативный характер. Реальные товары могут отличаться (цвет, комплектация, внешний вид и др.). «NLRE GROUP» SRL и её поставщики оставляют за собой право изменять технические характеристики товаров без предварительного уведомления.",
    "Описание товаров, технические характеристики и изображения предоставлены производителями или официальными представителями брендов. В связи с этим «NLRE GROUP» SRL не несёт ответственности за возможные неточности.",
    "Цены указаны с учётом НДС и действительны на момент подтверждения заказа.",
    "3. Заказ",
    "Оформление заказа на Сайте осуществляется путем:",
    "нажатия кнопки «Купить» и прохождения всех этапов оформления заказа, после чего оператор свяжется с вами для подтверждения наличия товара и заказа.",
    "Кнопка «Подтвердить заказ» не означает резервирование товара.",
    "Оформляя заказ, клиент подтверждает, что предоставленные данные являются точными и полными. В противном случае клиент несёт ответственность за возможные ошибки (задержка доставки, неверная доставка и др.).",
    "После оформления заказа «NLRE GROUP» SRL отправит подтверждение по электронной почте (если она указана) или свяжется по телефону. Это уведомление подтверждает только получение заказа, но не его принятие.",
    "Заказ считается подтверждённым только после телефонного подтверждения оператором до момента оплаты.",
    "Компания «NLRE GROUP» SRL вправе отказать в выполнении заказа без объяснения причин в следующих случаях:",
    "неоднократные неудачные попытки доставки",
    "неполные или некорректные данные клиента",
    "неуспешная или отклонённая онлайн-транзакция",
    "отказ банка-эмитента карты",
    "4. Доставка",
    "Доставка осуществляется только на территории Республики Молдова. Для каждого заказа допускается только один адрес доставки.",
    "Доставка осуществляется с понедельника по субботу. В воскресенье доставка не производится.",
    "Доставка осуществляется только заказанных товаров. Доставка нескольких товаров для выбора на месте не предусмотрена.",
    "Курьер не обязан осуществлять установку, подключение, демонстрацию или обучение пользованию товаром.",
    "В случае отказа от товара при доставке, если он соответствует заказу, клиент обязан оплатить стоимость доставки.",
    "Стоимость доставки:",
    "по Кишинёву — от 50 леев",
    "в другие населённые пункты — согласно тарифам курьерской службы",
    "Крупногабаритные товары доставляются до подъезда или ворот дома.",
    "Клиент обязан проверить товар при получении на предмет комплектности и отсутствия внешних дефектов.",
    "Возможен самовывоз из пункта выдачи:\nhttps://redlighttherapy.md/contacts",
    "Компания «NLRE GROUP» SRL не гарантирует наличие всех товаров на складе. В случае отсутствия товара клиент будет уведомлён, а оплаченные средства будут возвращены в срок до 30 дней.",
    "С согласия клиента может быть предложен аналогичный товар равного качества и стоимости.",
    "5. Право на отказ",
    "Потребитель (физическое лицо) имеет право отказаться от дистанционного договора в течение 14 календарных дней с момента:",
    "заключения договора, или",
    "получения товара",
    "Для этого необходимо подать письменное заявление и вернуть товар в первоначальном состоянии, в оригинальной упаковке, со всеми аксессуарами и документами.",
    "Заявление можно отправить по электронной почте:\nrlt@gmail.com",
    "Возврат денежных средств осуществляется в течение 14 дней с момента получения запроса, при условии возврата товара в надлежащем состоянии.",
    "Возврат производится тем же способом оплаты, без дополнительных комиссий.",
    "Если товар был использован, повреждён или укомплектован не полностью, «NLRE GROUP» SRL вправе удержать компенсацию за износ.",
    "Расходы на возврат товара несёт клиент.",
    "Для заказов с самовывозом товар резервируется на 48 часов. В этом случае право на отказ не применяется, так как договор заключается в торговом помещении.",
    "6. Оплата",
    "Оплата возможна:",
    "при доставке (наличными или банковской картой)",
    "онлайн банковской картой",
    "7. Гарантия",
    "Товары, приобретённые через сайт www.redlighttherapy.md, имеют гарантию производителя в соответствии с действующим законодательством.",
    "При доставке предоставляется гарантийный талон, действительный при наличии:",
    "гарантийного талона",
    "счета или кассового чека",
    "Адреса сервисных центров указаны на сайте:\nhttps://redlighttherapy.md/contacts",
    "8. Разрешение споров",
    "Все споры решаются путём переговоров.",
    "В случае невозможности урегулирования спора мирным путём, он передаётся на рассмотрение в компетентные судебные органы.",
  ],
  en: [
    "Terms and Conditions",
    "Terms and Conditions for the Use of the Online Store www.redlighttherapy.md",
    "1. General Information",
    "These Terms and Conditions (hereinafter referred to as the “Conditions”) apply to orders for the purchase of products and services offered by “NLRE GROUP” SRL through the website www.redlighttherapy.md (hereinafter referred to as the “Site”).",
    "By using this Site, you agree to the Conditions set forth by “NLRE GROUP” SRL, registered under fiscal code 1025600008673, VAT code 0212138, with its legal address at: Chișinău, Anton Crihan Street 20A.",
    "“NLRE GROUP” SRL reserves the right to modify these provisions, and the latest version will always be available on the Site under the “Terms and Conditions” section.",
    "We recommend that you carefully read these Conditions. This Site is intended for use by both individuals and legal entities placing orders for products or services offered by “NLRE GROUP” SRL.",
    "2. Product Description and Pricing",
    "By using the Site, you can obtain information about products and place purchase orders.",
    "Products are offered as presented on the Site and within the limits of available stock.",
    "Product images are for illustrative purposes only. Delivered products may differ from images (color, accessories, appearance, etc.). “NLRE GROUP” SRL and its suppliers reserve the right to modify product specifications without prior notice.",
    "Product descriptions, technical specifications, images, and symbols are based on information provided by manufacturers or brand representatives. Therefore, “NLRE GROUP” SRL does not assume responsibility for inaccuracies in product descriptions.",
    "All prices include VAT and are valid at the time of order confirmation.",
    "3. Orders",
    "When placing an order on the Site, you may do so by:",
    "Clicking the “Buy” button and completing all order steps, after which a consultant will contact you to confirm stock availability and the order.",
    "The “Confirm Order” option does not guarantee product reservation.",
    "By placing an order, the customer confirms that all provided data is accurate and complete. Any errors may result in delays or incorrect delivery.",
    "After placing an order, “NLRE GROUP” SRL will send a confirmation email (if an email address was provided) or contact you by phone. This email only confirms receipt of the order and does not constitute acceptance or conclusion of a contract.",
    "The order becomes valid only after confirmation by phone from an operator, prior to payment.",
    "“NLRE GROUP” SRL reserves the right to refuse an order without liability in the following cases:",
    "repeated failed deliveries",
    "incomplete or incorrect customer data",
    "failed or invalid online transactions",
    "refusal of the transaction by the issuing bank",
    "4. Delivery",
    "Delivery is available only within the Republic of Moldova. Each order may have only one delivery address.",
    "Deliveries are made Monday to Saturday. No deliveries are made on Sundays.",
    "Delivery is made only for ordered products. Delivering multiple products for on-site selection is not available.",
    "The courier is not responsible for installation, setup, demonstration, or instructions for product use.",
    "If the product meets all conditions but the customer refuses it upon delivery, the customer must cover delivery costs.",
    "Delivery costs vary depending on size and destination:",
    "Chișinău: starting from 50 MDL",
    "Other locations: according to courier tariffs",
    "Large items are delivered to the building entrance or house gate.",
    "Customers must check products upon delivery for completeness and visible defects.",
    "Customers may choose personal pickup from the location indicated on the Site:\nhttps://redlighttherapy.md/contacts",
    "“NLRE GROUP” LLC does not guarantee stock availability for all products. If a product is unavailable, the customer will be informed and refunded within a maximum of 30 days.",
    "With customer consent, a similar product of equal quality and price may be delivered.",
    "5. Right of Withdrawal",
    "Consumers (individuals) have the right to withdraw from a distance contract within 14 calendar days from:",
    "the date of contract conclusion, or",
    "the date of receiving the product",
    "To exercise this right, the customer must submit a written withdrawal request and return the product in its original condition, packaging, with all accessories and documents.",
    "Requests may also be sent by email to:\nrlt@gmail.com",
    "If withdrawal is made within 14 days, “NLRE GROUP” SRL will refund the payment within 14 days from receiving the request, provided the product is returned in perfect condition.",
    "Refunds will be made using the same payment method, without additional fees.",
    "If the product shows signs of use, damage, missing accessories, or altered condition, “NLRE GROUP” SRL may deduct compensation proportional to the depreciation, without exceeding the product’s full value.",
    "Return shipping costs are borne by the customer.",
    "For orders with in-store pickup, products are reserved for 48 hours. In this case, the right of withdrawal does not apply, as the contract is concluded in-store.",
    "6. Payment",
    "Payment may be made:",
    "upon delivery (cash or card)",
    "online via bank card",
    "7. Product Warranty",
    "Products purchased via www.redlighttherapy.md benefit from the manufacturer’s warranty in accordance with applicable laws.",
    "Products are delivered with a warranty certificate, valid only if accompanied by:",
    "warranty certificate",
    "purchase invoice and/or receipt",
    "Warranty service locations are listed at:\nhttps://redlighttherapy.md/contacts",
    "8. Dispute Resolution",
    "Any disputes will be resolved amicably.",
    "If an amicable resolution is not possible, disputes will be settled by the competent courts of law.",
  ],
};
