import type { Locale } from "@/data/masks";

export const privacyLegalBody: Record<Locale, readonly string[]> = {
  ro: [
    "Condițiile de Confidențialitate",
    "Datele cu caracter personal introduse în formularul de comandă vor fi folosite de către „NLRE GROUP” SRL doar pentru a procesa comanda dumneavoastră.",
    "Informațiile din formularul de comandă vor fi utilizate pentru a vă trimite confirmarea și procesarea comenzii (acces la comandă, confirmare, facturare, livrare) inclusiv orice informație promoțională periodică dacă ați acceptat să vă abonați la noutăți.",
    "Vânzătorul, „NLRE GROUP” SRL, se angajează să nu dezvăluie și să vîndă bazele de date care conțin informații cu privire la datele dvs. cu caracter personal, cu excepția cererilor din partea autorităților competente.",
    "„NLRE GROUP” SRL colectează următoarele date personale care vor fi specificate de clienți:",
    "1. Datele necesare pentru facturarea / livrarea comenzii. Ele sunt furnizate în mod voluntar de către client, respectiv, nume, prenume, adresa de livrare, telefon.",
    "2. Adresa de e-mail necesară pentru ca clienții să-și acceseze contul creat pe site-ul www.redlighttherapy.md și să schimbe datele de facturare / livrare.",
    "3. Adresa de e-mail, nume și prenume folosite în scopuri de marketing, pentru expedierea ofertelor pe e-mail și a  noutăților informative pentru clienții care au ales să se aboneze la newsletter.\n4. Toate datele cu caracter personal din e-mailul de confirmare / formularul de garanție / formularul de retur (respectiv, adresa de e-mail, numele, prenumele, datele de facturare / adresa de livrare) sunt stocate pentru a lua eventual legătura cu clientul pentru a rezolva anumite situații cu privire la returnare, garanții etc.",
    "5. Folosind o soluție integrată, clientul poate alege plata online pentru comandă. Toate tipurile de carduri emise de băncile din Republica Moldova și străine sub siglele Visa și MasterCard sunt acceptate, cu condiția că sunt activate pentru plățile online de băncile emitente.",
    "„NLRE GROUP” SRL, sub nici o formă nu stochează informații despre cardul bancar al clientului, ea este procesată direct pe serverele furnizorului de servicii de plată online. Excepție fiind situația cînd ne furnizați detaliile contului dvs. bancar pentru o rambursare în cazul returnării unui produs, numai în acest caz colectăm și prelucrăm aceste date.",
    "6. Când utilizați cookie-uri, vor fi colectate următoarele date:",
    "Adresa IP al utilizatorului;",
    "data și ora de intrare;",
    "titlul paginii;",
    "ID-ul sesiunii;",
    "URL-ul de referință (de la care ați accesat pagina noastră web);",
    "cantitatea de date transferate;",
    "tipul browserului;",
    "sistemul de operare;",
    "În conformitate cu legea nr. 133 / 08.07.2011 privind protecția datelor cu caracter personal, „NLRE GROUP” SRL garantează protecția maximă a datelor cu caracter personal ale cumpărătorilor împotriva distrugerii, modificării, blocării, copierii, distribuției, precum și a altor acțiuni ilegale care ar putea pune în pericol drepturile cumpărătorului.",
    "Astfel, „NLRE GROUP” SRL prelucrează datele numai în scopurile specificate.",
    "Cumpărătorii beneficiază de drepturile prevăzute în legea nr. 133 / 08.07.2011 privind protecția datelor cu caracter personal: dreptul la informație, accesul la date, dreptul de a interveni, dreptul de a merge în instanță în cazul încălcării drepturilor sale.",
    "Cumpărătorul are dreptul să solicite ștergerea completă sau parțială a datelor cu caracter personal, precum și a contului de utilizator. Clientul își poate exercita oricare dintre drepturile de mai sus prin trimiterea unei cereri scrise la adresa proprietarului: Chișinău, str. Anton Crihan 20A, tel. +373 68 922 229, e-mail info@redlighttherapy.md.",
    "Măsuri de securitate pentru protejarea datelor cu caracter personal:",
    "1. Prezența unei clauze de confidențialitate în contractul angajaților autorizați să prelucreze datele cu caracter personal.\n2. Prelucrarea datelor cu caracter personal se realizează automat, în conformitate cu cerințele legii și în condiții care asigură securitatea, confidențialitatea și respectarea drepturilor persoanelor vizate.\n3. Certificatul de securitate este instalat pe serverul pe care sunt colectate datele personale.\n4. Afișarea politicii de confidențialitate pe site-ul companiei: www.redlighttherapy.md\n5. Accesul la baza de date în care sunt stocate datele personale se realizează numai de către angajații „NLRE GROUP” SRL prin introducerea unui nume de utilizator și a unei parole.",
    "„NLRE GROUP” SRL poate furniza datele dvs. personale altor companii cu care încheiem parteneriate, dar numai pe baza unei obligații de confidențialitate, care asigură că aceste date sunt păstrate în siguranță și că furnizarea acestor informații personale se realizează în conformitate cu legislația în vigoare, și anume: furnizori de servicii de curierat, servicii bancare, alte companii cu care putem dezvolta programe comune pentru a oferi produsele și serviciile noastre pe piață, care vor opera în cadrul și cu scopurile stabilite de „NLRE GROUP” SRL în conformitate cu termenii politicii stabilite.",
  ],
  ru: [
    "Политика конфиденциальности",
    "Ваши личные данные будут использоваться „NLRE GROUP” S.R.L. только для для выполнения вашего заказа. Информация в форме заказа будет использоваться для отправки вам подтверждения и обработки заказов (доступ к заказу, подтверждение, выставление счетов, доставка), любых рекламных акций и периодических информационных рассылок, если Вы согласились подписаться на рассылку. Продавец обязуется не разглашать и продавать базы данных, содержащие информацию, касающуюся ваших персональных данных, за исключением запросов уполномоченных контрольных органов.",
    "«NLRE GROUP” SRL собирает следующие персональные данные указанные клиентами:",
    "1. Данные, необходимые для выставления счета / доставки заказов, предоставляются добровольно, соответственно имя, фамилия, адрес доставки, телефон.",
    "2. Адрес электронной почты, необходимый клиентам для доступа к своей учетной записи, созданной на веб-сайте www.redlighttherapy.md, и для изменения данных выставления счетов / доставки.",
    "3. Адрес электронной почты, имя и фамилия, в маркетинговых целях, соответственно, для передачи по электронной почте предложений и информационной рассылки для клиентов, которые выбрали подписку на рассылку.",
    "4. Все личные данные в электронном письме с подтверждением / гарантийной формой / формой возврата (соответственно, адрес электронной почты, имя, фамилия, адрес для выставления счета / адрес доставки) хранятся для связи с клиентом с целью разрешения определенных ситуаций, касающихся возврата, гарантий и.т.д.",
    "5. С помощью интегрированного решения, клиент может выбирать онлайн-оплату заказа. Принимаются все типы карт, выпущенные молдавскими и иностранными банками под логотипами Visa и MasterCard, при условии, что банки-эмитенты активировали их для онлайн-платежей.",
    "SRL „NLRE GROUP”, никоим образом не хранит информацию о банковской карте клиента, она обрабатывается непосредственно на серверах поставщика услуг онлайн-платежей. Исключением из этого является ситуация, когда вы предоставляете нам реквизиты своего банковского счета для возврата в случае возврата продукта, только в этом случае мы собираем и обрабатываем эти данные.",
    "6. При использовании Cookies будут собираться следующие данные:",
    "IP-адрес пользователя;",
    "дата и время входа;",
    "название страницы;",
    "ID сеанса;",
    "ссылочный URL (с которого вы перешли на нашу веб-страницу);",
    "количество передаваемых данных;",
    "тип браузера;",
    "операционная система;",
    "В соответствии с законом №. 133/08.07.2011 о защите персональных данных, „NLRE GROUP” SRL гарантирует максимальную защиту личных данных покупателей от уничтожения, изменения, блокирования, копирования, распространения, а также другие незаконные действия, которые могут поставить под угрозу права покупателя.",
    "Таким образом, „NLRE GROUP” SRL обрабатывает данные только для указанных целей.",
    "Покупатели пользуются правами, предусмотренными Законом №. 133/08.07.2011 о защите персональных данных: право на информацию, доступ к данным, право на вмешательство, право выступать против, право не зависеть от индивидуальных решений, право обращаться в суд в случае нарушения его прав.",
    "Покупатель имеет право потребовать полного или частичного удаления личных данных, а также учетной записи пользователя. Клиент может воспользоваться любым из вышеперечисленных прав, подав письменный запрос, на адрес владельца: г. Кишинев, ул. Антон Крихан, 20A, тел. +373 68 922 229, e-mail info@redlighttherapy.md.",
    "Меры безопасности для защиты персональных данных:",
    "1. Наличие оговорки о конфиденциальности в договоре сотрудников, уполномоченных на обработку персональных данных.",
    "2. Обработка персональных данных осуществляется автоматически, в соответствии с требованиями законодательства и в условиях, обеспечивающих безопасность, конфиденциальность и соблюдение прав субъектов данных.",
    "3. Сертификат безопасности установлен на сервере, на котором собраны персональные данные.",
    "4. Отображение политики конфиденциальности на сайте компании: www.redlighttherapy.md",
    "5. Доступ к базе данных, в которой хранятся персональные данные, осуществляется только сотрудниками компании „NLRE GROUP” SRL путем ввода имени пользователя и идентификационного пароля.",
    "„NLRE GROUP” S.R.L может предоставлять ваши персональные данные другим компаниям, с которыми мы вступаем в партнерские отношения, но только на основе обязательства конфиденциальности, которое гарантирует, что эти данные хранятся в безопасности и что предоставление этой личной информации осуществляется в соответствии с действующим законодательством, а именно: поставщики курьерских услуг, банковские услуги, другие компании, с которыми мы можем разработать совместные программы для предложения на рынке наших продуктов и услуг, действующие в рамках и целях, установленных „NLRE GROUP” S.R.L, в соответствии с условиями настоящей Политики.",
  ],
  en: [
    "Privacy Policy",
    "The personal data entered in the order form will be used by “NLRE GROUP” SRL solely for processing your order.",
    "The information provided in the order form will be used to send order confirmations and to process the order (order access, confirmation, invoicing, delivery), including periodic promotional information if you have agreed to subscribe to updates.",
    "The Seller, “NLRE GROUP” SRL, undertakes not to disclose or sell databases containing your personal data, except in response to requests from competent authorities.",
    "“NLRE GROUP” SRL collects the following personal data provided by customers:",
    "Data necessary for invoicing and delivery, voluntarily provided by the customer, namely: name, surname, delivery address, phone number.",
    "Email address, required for customers to access their account created on the website www.redlighttherapy.md and to modify billing/delivery details.",
    "Email address, name, and surname used for marketing purposes, including sending offers and informational newsletters to customers who have subscribed.",
    "Personal data included in confirmation emails / warranty forms / return forms (such as email address, name, surname, billing details, delivery address) are stored to allow communication with the customer regarding returns, warranties, and related matters.",
    "Online payments: Customers may choose to pay online using an integrated solution. All cards issued by banks in the Republic of Moldova and abroad under Visa and MasterCard are accepted, provided they are enabled for online payments.",
    "“NLRE GROUP” SRL does not store any bank card information. Payment data is processed directly on the servers of the online payment service provider.",
    "Exception: if you provide bank account details for refunds in case of product returns, such data will be collected and processed strictly for that purpose.",
    "When using cookies, the following data may be collected:",
    "User IP address",
    "Date and time of access",
    "Page title",
    "Session ID",
    "Referring URL",
    "Amount of data transferred",
    "Browser type",
    "Operating system",
    "Data Protection",
    "In accordance with Law No. 133 of 08.07.2011 on Personal Data Protection, “NLRE GROUP” SRL guarantees the maximum protection of customers’ personal data against destruction, modification, blocking, copying, distribution, and other illegal actions.",
    "Thus, personal data is processed only for the specified purposes.",
    "Customers benefit from the rights provided by Law No. 133/2011, including:",
    "the right to information",
    "the right of access to data",
    "the right to rectification",
    "the right to seek legal remedy in case of violations",
    "Customers have the right to request the full or partial deletion of personal data, as well as deletion of their user account.",
    "These rights can be exercised by submitting a written request to the owner at:\nChișinău, Anton Crihan Street 20A, phone +373 68 922 229, info@redlighttherapy.md",
    "Security Measures for Personal Data Protection",
    "Inclusion of confidentiality clauses in contracts with employees authorized to process personal data.",
    "Automated processing of personal data in compliance with legal requirements, ensuring security, confidentiality, and protection of data subjects’ rights.",
    "Installation of an SSL security certificate on the server where personal data is collected.",
    "Publication of the Privacy Policy on the company’s website: www.redlighttherapy.md",
    "Access to the database containing personal data is restricted to authorized employees of “NLRE GROUP” SRL, based on username and password authentication.",
    "Data Sharing",
    "“NLRE GROUP” SRL may provide your personal data to partner companies, only under confidentiality obligations and in compliance with applicable legislation, including:",
    "courier service providers",
    "banking/payment service providers",
    "other companies involved in joint programs for offering products and services",
    "These partners will process data strictly within the scope and purposes established by “NLRE GROUP” SRL, in accordance with this Privacy Policy.",
  ],
};
